apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-gpu
  namespace: tenant-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-gpu
  template:
    metadata:
      labels:
        app: fake-gpu
    spec:
      containers:
      - name: exporter
        image: python:3.11
        command:
          - /bin/sh
          - -c
          - |
            pip install prometheus_client && \
            python -c "
            from prometheus_client import start_http_server, Gauge
            import random, time
            g = Gauge('dcgm_gpu_utilization', 'fake gpu')
            start_http_server(9400)
            while True:
                g.set(random.randint(10,90))
                time.sleep(2)
            "
        ports:
        - containerPort: 9400
