apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-proxy
  namespace: tenant-b
  labels:
    app: litellm
    tenant: tenant-b
spec:
  replicas: 1  # Tenant B 較小方案，只有 1 個副本
  selector:
    matchLabels:
      app: litellm
      tenant: tenant-b
  template:
    metadata:
      labels:
        app: litellm
        tenant: tenant-b
    spec:
      serviceAccountName: tenant-b-sa
      containers:
      - name: litellm
        image: ghcr.io/berriai/litellm:main-latest
        ports:
        - containerPort: 4000
          name: http
        env:
        - name: OPENAI_API_KEY
          value: "your-openai-key-here"
        volumeMounts:
        - name: config
          mountPath: /app/config.yaml
          subPath: config.yaml
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: litellm-config