apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-a-quota
  namespace: tenant-a
spec:
  hard:
    requests.cpu: "8"
    limits.cpu: "12"
    requests.memory: 32Gi
    limits.memory: 40Gi
    pods: "20"
