apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit
  namespace: tenant-a
spec:
  limits:
  - default:
      cpu: "1"
      memory: 1Gi
    defaultRequest:
      cpu: 500m
      memory: 256Mi
    type: Container
