apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-b-quota
  namespace: tenant-b
spec:
  hard:
    requests.cpu: "4"
    limits.cpu: "6"
    requests.memory: 16Gi
    limits.memory: 20Gi
    pods: "10"
