apiVersion: v1
kind: Namespace
metadata:
  name: tenant-a
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-b


# kubectl apply -f tenant-quota.yaml
# kubectl get namespace
# kubectl get resourcequota -n tenant-a
